import styles from './layout.module.scss'
import _ from 'lodash'

import Navbar from '@/components/Navbar/page'
import Footer from '@/components/Footer/page'
import ReduxProvider from '../util/reduxProviders'

import AuthJudge from '@/util/authJudge/page'
import SessionProviders from '@/util/sessionProviders'
require("dotenv").config()

export const metadata = {
  title: 'dev Panseung',
  description: 'Generated by dev Panseung',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
      <body className={styles['layout']}>
        <ReduxProvider>          
          <SessionProviders>
            <AuthJudge></AuthJudge>
          </SessionProviders>
          <Navbar></Navbar>
            {children}
        </ReduxProvider>
        <Footer></Footer>
      </body>
    </html>
  )
}
