import styles from './layout.module.scss'

import Navbar from '@/components/Navbar/page'
import Footer from '@/components/Footer/page'
import Head from 'next/head'

export const metadata = {
  title: 'dev Panseung',
  description: 'Generated by dev Panseung',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>hi</title>
        <meta property='custom' content='123123'></meta>
      </Head>
      
      <body className={styles['layout']}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
