import styles from './layout.module.scss'

import Navbar from '@/components/Navbar/page'
import Footer from '@/components/Footer/page'
import Head from 'next/head'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'dev Panseung',
  description: 'Generated by dev Panseung',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let session :Object | null = await getServerSession( authOptions )
  let isLogin :Boolean = session ? true : false

  return (
    <html lang="en">
      <Head>
        <title>hi</title>
        <meta property='custom' content='123123'></meta>
      </Head>
      
      <body className={styles['layout']}>
        <Navbar isLogin = { isLogin } ></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
